# Generated by Django 5.2.1 on 2025-07-17 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hubs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("switch", "Switch"),
                            ("dimmer", "Dimmer"),
                            ("lock", "Lock"),
                            ("thermostat", "Thermostat"),
                        ],
                        max_length=20,
                    ),
                ),
                ("state", models.JSONField(default=dict)),
                ("paired", models.BooleanField(default=False)),
                (
                    "hub",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="devices",
                        to="hubs.hub",
                    ),
                ),
            ],
        ),
    ]
